config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  mount_uploaders :photos, PhotoUploader
  serialize :photos, JSON # If you use SQLite, add this line.
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def new
    @comment = Comment.new
  end

  def create
    params[:comment][:user_id] = current_user.id
    params[:comment][:post_id] = @post.id
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_path(@post.id)
    else
      render 'new'
    end

  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

private
  def set_post
    @post = Post.find_by(id: params[:post_id])
  end

   def comment_params
    params.require(:comment).permit(:user_id, :post_id, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except:[:index, :show]
  before_action :post_find, only: [:show, :edit, :update, :destroy]
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = "Post successfully created"
      redirect_to root_path
    else
      flash[:error] = "Post has error with created"
      render 'new'
    end
  end

  def show
     @comments = @post.comments
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post successfully updated"
      redirect_to post_path(@post.id)
    else
      flash[:error] = "Post has error with created"
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end
private
  def post_find
   @post = Post.find_by(id: params[:id])
  end

  def post_params
   params.require(:post).permit(:user_id, :title, :body, {photos: []})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/new.html.erb
<h1>Add your comment</h1>
<%= form_for @comment, url: post_comments_path(@post.id) do |f| %>

 <% if @comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@comment.errors.count, "error") %> </h2>

     <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

   Comment: <%= f.text_area :body, size: "60x12" %><br />
  <%= f.submit %>
<% end %>

app/views/layouts/_header.html.erb
<%= link_to 'Home',root_path %> | <%= link_to "Add new post", new_post_path %> |
<% if user_signed_in? %>
  User: <%= current_user.email.split('@').first %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAnimeCollection</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |f| %>

<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <%= f.text_field :title %><br />
  <%= f.text_area :body, size: "60x12" %><br />
  <%= f.file_field :photos, multiple: true %> <br> <br>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit your post</h1>
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>My Anime Collection</h1>
<div align = "right">
  <%= search_form_for @q do |f| %>
    <%= f.search_field :title_cont %>
    <%= f.submit %>
  <% end %>
</div>

<% @posts.each do |p| %>
  <%= link_to p.title, post_path(p.id) %> <br>
  <%= p.body %>
  <hr>
<% end %>

app/views/posts/new.html.erb
<h1>Add your post</h1>
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<h3> <%= @post.body %> </h3>
<% @post.photos.each do | photo | %>
	<%= image_tag(photo.url, size: "800x600")%>	<br> <br>
<% end %>
  <p><%= link_to "Write Comment", new_post_comment_path(@post.id) %></p>
<% @comments.each do |comment| %>
  <p>
  User <b><%= comment.user.email.split('@').first%></b> write: <br />
  <%= comment.body %> <br>
  <% if user_signed_in? %>
    <% if comment.user_id == current_user.id %>
      <%= link_to "Delete comment", post_path(@post.id), method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
  <% end %>
  </p>
<% end %>
<% if user_signed_in? %>
  <% if @post.user_id == current_user.id %>
    <hr>
    <%= link_to "Edit", edit_post_path %> |
    <%= link_to "Delete", post_path(@post.id), method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>
<% end %>